/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package saas.identity.shared.api;

import saas.identity.shared.dto.AdminClientsListClients200Response;
import saas.identity.shared.dto.AdminClientsSetClientStatusRequest;
import saas.identity.shared.dto.CreateOAuthClientRequest;
import saas.identity.shared.dto.ErrorResponse;
import org.springframework.lang.Nullable;
import saas.identity.shared.dto.OAuthClient;
import saas.identity.shared.dto.UpdateOAuthClientRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-10T10:23:40.344575800+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "admin-clients", description = "the admin-clients API")
public interface AdminClientsApi {

    String PATH_ADMIN_CLIENTS_CREATE_CLIENT = "/api/v1/admin/clients";
    /**
     * POST /api/v1/admin/clients
     *
     * @param createOAuthClientRequest  (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code 200)
     */
    @Operation(
        operationId = "adminClientsCreateClient",
        tags = { "admin-clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The request has succeeded.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OAuthClient.class))
            }),
            @ApiResponse(responseCode = "default", description = "An unexpected error response.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminClientsApi.PATH_ADMIN_CLIENTS_CREATE_CLIENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<OAuthClient> adminClientsCreateClient(
        @Parameter(name = "CreateOAuthClientRequest", description = "", required = true) @Valid @RequestBody CreateOAuthClientRequest createOAuthClientRequest
    );


    String PATH_ADMIN_CLIENTS_DELETE_CLIENT = "/api/v1/admin/clients/{clientId}";
    /**
     * DELETE /api/v1/admin/clients/{clientId}
     *
     * @param clientId  (required)
     * @return There is no content to send for this request, but the headers may be useful.  (status code 204)
     *         or An unexpected error response. (status code 200)
     */
    @Operation(
        operationId = "adminClientsDeleteClient",
        tags = { "admin-clients" },
        responses = {
            @ApiResponse(responseCode = "204", description = "There is no content to send for this request, but the headers may be useful. "),
            @ApiResponse(responseCode = "default", description = "An unexpected error response.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = AdminClientsApi.PATH_ADMIN_CLIENTS_DELETE_CLIENT,
        produces = { "application/json" }
    )
    ResponseEntity<Void> adminClientsDeleteClient(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") String clientId
    );


    String PATH_ADMIN_CLIENTS_GET_CLIENT = "/api/v1/admin/clients/{clientId}";
    /**
     * GET /api/v1/admin/clients/{clientId}
     *
     * @param clientId  (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code 200)
     */
    @Operation(
        operationId = "adminClientsGetClient",
        tags = { "admin-clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The request has succeeded.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OAuthClient.class))
            }),
            @ApiResponse(responseCode = "default", description = "An unexpected error response.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdminClientsApi.PATH_ADMIN_CLIENTS_GET_CLIENT,
        produces = { "application/json" }
    )
    ResponseEntity<OAuthClient> adminClientsGetClient(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") String clientId
    );


    String PATH_ADMIN_CLIENTS_LIST_CLIENTS = "/api/v1/admin/clients";
    /**
     * GET /api/v1/admin/clients
     *
     * @param page  (optional)
     * @param pageSize  (optional)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code 200)
     */
    @Operation(
        operationId = "adminClientsListClients",
        tags = { "admin-clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The request has succeeded.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminClientsListClients200Response.class))
            }),
            @ApiResponse(responseCode = "default", description = "An unexpected error response.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdminClientsApi.PATH_ADMIN_CLIENTS_LIST_CLIENTS,
        produces = { "application/json" }
    )
    ResponseEntity<AdminClientsListClients200Response> adminClientsListClients(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) @Nullable Integer page,
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageSize", required = false) @Nullable Integer pageSize
    );


    String PATH_ADMIN_CLIENTS_SET_CLIENT_STATUS = "/api/v1/admin/clients/{clientId}/status";
    /**
     * PATCH /api/v1/admin/clients/{clientId}/status
     *
     * @param clientId  (required)
     * @param adminClientsSetClientStatusRequest  (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code 200)
     */
    @Operation(
        operationId = "adminClientsSetClientStatus",
        tags = { "admin-clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The request has succeeded.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OAuthClient.class))
            }),
            @ApiResponse(responseCode = "default", description = "An unexpected error response.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = AdminClientsApi.PATH_ADMIN_CLIENTS_SET_CLIENT_STATUS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<OAuthClient> adminClientsSetClientStatus(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") String clientId,
        @Parameter(name = "AdminClientsSetClientStatusRequest", description = "", required = true) @Valid @RequestBody AdminClientsSetClientStatusRequest adminClientsSetClientStatusRequest
    );


    String PATH_ADMIN_CLIENTS_UPDATE_CLIENT = "/api/v1/admin/clients/{clientId}";
    /**
     * PATCH /api/v1/admin/clients/{clientId}
     *
     * @param clientId  (required)
     * @param updateOAuthClientRequest  (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code 200)
     */
    @Operation(
        operationId = "adminClientsUpdateClient",
        tags = { "admin-clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The request has succeeded.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OAuthClient.class))
            }),
            @ApiResponse(responseCode = "default", description = "An unexpected error response.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = AdminClientsApi.PATH_ADMIN_CLIENTS_UPDATE_CLIENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<OAuthClient> adminClientsUpdateClient(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") String clientId,
        @Parameter(name = "UpdateOAuthClientRequest", description = "", required = true) @Valid @RequestBody UpdateOAuthClientRequest updateOAuthClientRequest
    );

}
