/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package saas.identity.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import saas.identity.shared.dto.LoginRequest;
import saas.identity.shared.dto.LoginResponse;
import saas.identity.shared.dto.SessionsLoginDefaultResponse;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-09-19T11:42:08.525926500+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "auth", description = "the auth API")
public interface AuthApi {

  String PATH_SESSIONS_LOGIN = "/api/v1/auth/login";

  /**
   * POST /api/v1/auth/login
   *
   * @param loginRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "sessionsLogin",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = LoginResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = SessionsLoginDefaultResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_SESSIONS_LOGIN,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<LoginResponse> sessionsLogin(
      @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody
          LoginRequest loginRequest);

  String PATH_SESSIONS_LOGOUT = "/api/v1/auth/logout";

  /**
   * POST /api/v1/auth/logout
   *
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204)
   */
  @Operation(
      operationId = "sessionsLogout",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. ")
      })
  @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_SESSIONS_LOGOUT)
  ResponseEntity<Void> sessionsLogout();
}
