/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package saas.identity.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import saas.identity.shared.dto.CreateRoleRequest;
import saas.identity.shared.dto.ErrorResponse;
import saas.identity.shared.dto.Role;
import saas.identity.shared.dto.TenantRolesListRoles200Response;
import saas.identity.shared.dto.TenantRolesSetPermissionsRequest;
import saas.identity.shared.dto.UpdateRoleRequest;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-13T23:52:54.053972+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "tenant-roles", description = "the tenant-roles API")
public interface TenantRolesApi {

  String PATH_TENANT_ROLES_CREATE_ROLE = "/api/v1/tenants/{tenantId}/roles";

  /**
   * POST /api/v1/tenants/{tenantId}/roles
   *
   * @param tenantId (required)
   * @param createRoleRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantRolesCreateRole",
      tags = {"tenant-roles"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Role.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = TenantRolesApi.PATH_TENANT_ROLES_CREATE_ROLE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Role> tenantRolesCreateRole(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "CreateRoleRequest", description = "", required = true) @Valid @RequestBody
          CreateRoleRequest createRoleRequest);

  String PATH_TENANT_ROLES_DELETE_ROLE = "/api/v1/tenants/{tenantId}/roles/{roleId}";

  /**
   * DELETE /api/v1/tenants/{tenantId}/roles/{roleId}
   *
   * @param tenantId (required)
   * @param roleId (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "tenantRolesDeleteRole",
      tags = {"tenant-roles"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = TenantRolesApi.PATH_TENANT_ROLES_DELETE_ROLE,
      produces = {"application/json"})
  ResponseEntity<Void> tenantRolesDeleteRole(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "roleId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("roleId")
          String roleId);

  String PATH_TENANT_ROLES_GET_ROLE = "/api/v1/tenants/{tenantId}/roles/{roleId}";

  /**
   * GET /api/v1/tenants/{tenantId}/roles/{roleId}
   *
   * @param tenantId (required)
   * @param roleId (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantRolesGetRole",
      tags = {"tenant-roles"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Role.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = TenantRolesApi.PATH_TENANT_ROLES_GET_ROLE,
      produces = {"application/json"})
  ResponseEntity<Role> tenantRolesGetRole(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "roleId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("roleId")
          String roleId);

  String PATH_TENANT_ROLES_LIST_ROLES = "/api/v1/tenants/{tenantId}/roles";

  /**
   * GET /api/v1/tenants/{tenantId}/roles
   *
   * @param tenantId (required)
   * @param page (optional)
   * @param pageSize (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantRolesListRoles",
      tags = {"tenant-roles"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TenantRolesListRoles200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = TenantRolesApi.PATH_TENANT_ROLES_LIST_ROLES,
      produces = {"application/json"})
  ResponseEntity<TenantRolesListRoles200Response> tenantRolesListRoles(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize);

  String PATH_TENANT_ROLES_SET_PERMISSIONS =
      "/api/v1/tenants/{tenantId}/roles/{roleId}/permissions";

  /**
   * PUT /api/v1/tenants/{tenantId}/roles/{roleId}/permissions
   *
   * @param tenantId (required)
   * @param roleId (required)
   * @param tenantRolesSetPermissionsRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantRolesSetPermissions",
      tags = {"tenant-roles"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Role.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = TenantRolesApi.PATH_TENANT_ROLES_SET_PERMISSIONS,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Role> tenantRolesSetPermissions(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "roleId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("roleId")
          String roleId,
      @Parameter(name = "TenantRolesSetPermissionsRequest", description = "", required = true)
          @Valid
          @RequestBody
          TenantRolesSetPermissionsRequest tenantRolesSetPermissionsRequest);

  String PATH_TENANT_ROLES_UPDATE_ROLE = "/api/v1/tenants/{tenantId}/roles/{roleId}";

  /**
   * PATCH /api/v1/tenants/{tenantId}/roles/{roleId}
   *
   * @param tenantId (required)
   * @param roleId (required)
   * @param updateRoleRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantRolesUpdateRole",
      tags = {"tenant-roles"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Role.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PATCH,
      value = TenantRolesApi.PATH_TENANT_ROLES_UPDATE_ROLE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Role> tenantRolesUpdateRole(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "roleId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("roleId")
          String roleId,
      @Parameter(name = "UpdateRoleRequest", description = "", required = true) @Valid @RequestBody
          UpdateRoleRequest updateRoleRequest);
}
