/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package saas.identity.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import saas.identity.shared.dto.AdminTenantsListTenants200Response;
import saas.identity.shared.dto.CreateTenantRequest;
import saas.identity.shared.dto.ErrorResponse;
import saas.identity.shared.dto.Tenant;
import saas.identity.shared.dto.UpdateTenantRequest;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-13T19:43:32.481885100+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "admin-tenants", description = "the admin-tenants API")
public interface AdminTenantsApi {

  String PATH_ADMIN_TENANTS_CREATE_TENANT = "/api/v1/admin/tenants";

  /**
   * POST /api/v1/admin/tenants
   *
   * @param createTenantRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminTenantsCreateTenant",
      tags = {"admin-tenants"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Tenant.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AdminTenantsApi.PATH_ADMIN_TENANTS_CREATE_TENANT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Tenant> adminTenantsCreateTenant(
      @Parameter(name = "CreateTenantRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateTenantRequest createTenantRequest);

  String PATH_ADMIN_TENANTS_DELETE_TENANT = "/api/v1/admin/tenants/{id}";

  /**
   * DELETE /api/v1/admin/tenants/{id}
   *
   * @param id (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "adminTenantsDeleteTenant",
      tags = {"admin-tenants"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = AdminTenantsApi.PATH_ADMIN_TENANTS_DELETE_TENANT,
      produces = {"application/json"})
  ResponseEntity<Void> adminTenantsDeleteTenant(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_ADMIN_TENANTS_GET_TENANT = "/api/v1/admin/tenants/{id}";

  /**
   * GET /api/v1/admin/tenants/{id}
   *
   * @param id (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminTenantsGetTenant",
      tags = {"admin-tenants"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Tenant.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = AdminTenantsApi.PATH_ADMIN_TENANTS_GET_TENANT,
      produces = {"application/json"})
  ResponseEntity<Tenant> adminTenantsGetTenant(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_ADMIN_TENANTS_LIST_TENANTS = "/api/v1/admin/tenants";

  /**
   * GET /api/v1/admin/tenants
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminTenantsListTenants",
      tags = {"admin-tenants"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = AdminTenantsListTenants200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = AdminTenantsApi.PATH_ADMIN_TENANTS_LIST_TENANTS,
      produces = {"application/json"})
  ResponseEntity<AdminTenantsListTenants200Response> adminTenantsListTenants(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize);

  String PATH_ADMIN_TENANTS_UPDATE_TENANT = "/api/v1/admin/tenants/{id}";

  /**
   * PATCH /api/v1/admin/tenants/{id}
   *
   * @param id (required)
   * @param updateTenantRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminTenantsUpdateTenant",
      tags = {"admin-tenants"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Tenant.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PATCH,
      value = AdminTenantsApi.PATH_ADMIN_TENANTS_UPDATE_TENANT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Tenant> adminTenantsUpdateTenant(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id,
      @Parameter(name = "UpdateTenantRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateTenantRequest updateTenantRequest);
}
