/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package saas.identity.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import saas.identity.shared.dto.AdminOAuthAppsAuthorize200Response;
import saas.identity.shared.dto.AdminOAuthAppsListOAuthApps200Response;
import saas.identity.shared.dto.AuthorizeCodeRequest;
import saas.identity.shared.dto.CreateOAuthAppRequest;
import saas.identity.shared.dto.ErrorResponse;
import saas.identity.shared.dto.OAuthApp;
import saas.identity.shared.dto.TokenRequest;
import saas.identity.shared.dto.TokenResponse;
import saas.identity.shared.dto.UpdateOAuthAppRequest;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-12T13:11:49.950871300+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "admin-oauth-apps", description = "the admin-oauth-apps API")
public interface AdminOauthAppsApi {

  String PATH_ADMIN_O_AUTH_APPS_AUTHORIZE = "/api/v1/admin/oauth-apps/authorize";

  /**
   * POST /api/v1/admin/oauth-apps/authorize
   *
   * @param authorizeCodeRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminOAuthAppsAuthorize",
      tags = {"admin-oauth-apps"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = AdminOAuthAppsAuthorize200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AdminOauthAppsApi.PATH_ADMIN_O_AUTH_APPS_AUTHORIZE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<AdminOAuthAppsAuthorize200Response> adminOAuthAppsAuthorize(
      @Parameter(name = "AuthorizeCodeRequest", description = "", required = true)
          @Valid
          @RequestBody
          AuthorizeCodeRequest authorizeCodeRequest);

  String PATH_ADMIN_O_AUTH_APPS_CREATE_O_AUTH_APP = "/api/v1/admin/oauth-apps";

  /**
   * POST /api/v1/admin/oauth-apps
   *
   * @param createOAuthAppRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminOAuthAppsCreateOAuthApp",
      tags = {"admin-oauth-apps"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = OAuthApp.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AdminOauthAppsApi.PATH_ADMIN_O_AUTH_APPS_CREATE_O_AUTH_APP,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<OAuthApp> adminOAuthAppsCreateOAuthApp(
      @Parameter(name = "CreateOAuthAppRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateOAuthAppRequest createOAuthAppRequest);

  String PATH_ADMIN_O_AUTH_APPS_DELETE_O_AUTH_APP = "/api/v1/admin/oauth-apps/{appId}";

  /**
   * DELETE /api/v1/admin/oauth-apps/{appId}
   *
   * @param appId (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "adminOAuthAppsDeleteOAuthApp",
      tags = {"admin-oauth-apps"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = AdminOauthAppsApi.PATH_ADMIN_O_AUTH_APPS_DELETE_O_AUTH_APP,
      produces = {"application/json"})
  ResponseEntity<Void> adminOAuthAppsDeleteOAuthApp(
      @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("appId")
          String appId);

  String PATH_ADMIN_O_AUTH_APPS_GET_O_AUTH_APP = "/api/v1/admin/oauth-apps/{appId}";

  /**
   * GET /api/v1/admin/oauth-apps/{appId}
   *
   * @param appId (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminOAuthAppsGetOAuthApp",
      tags = {"admin-oauth-apps"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = OAuthApp.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = AdminOauthAppsApi.PATH_ADMIN_O_AUTH_APPS_GET_O_AUTH_APP,
      produces = {"application/json"})
  ResponseEntity<OAuthApp> adminOAuthAppsGetOAuthApp(
      @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("appId")
          String appId);

  String PATH_ADMIN_O_AUTH_APPS_LIST_O_AUTH_APPS = "/api/v1/admin/oauth-apps";

  /**
   * GET /api/v1/admin/oauth-apps
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminOAuthAppsListOAuthApps",
      tags = {"admin-oauth-apps"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = AdminOAuthAppsListOAuthApps200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = AdminOauthAppsApi.PATH_ADMIN_O_AUTH_APPS_LIST_O_AUTH_APPS,
      produces = {"application/json"})
  ResponseEntity<AdminOAuthAppsListOAuthApps200Response> adminOAuthAppsListOAuthApps(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize);

  String PATH_ADMIN_O_AUTH_APPS_TOKEN = "/api/v1/admin/oauth-apps/token";

  /**
   * POST /api/v1/admin/oauth-apps/token
   *
   * @param tokenRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminOAuthAppsToken",
      tags = {"admin-oauth-apps"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TokenResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AdminOauthAppsApi.PATH_ADMIN_O_AUTH_APPS_TOKEN,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<TokenResponse> adminOAuthAppsToken(
      @Parameter(name = "TokenRequest", description = "", required = true) @Valid @RequestBody
          TokenRequest tokenRequest);

  String PATH_ADMIN_O_AUTH_APPS_UPDATE_O_AUTH_APP = "/api/v1/admin/oauth-apps/{appId}";

  /**
   * PATCH /api/v1/admin/oauth-apps/{appId}
   *
   * @param appId (required)
   * @param updateOAuthAppRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "adminOAuthAppsUpdateOAuthApp",
      tags = {"admin-oauth-apps"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = OAuthApp.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PATCH,
      value = AdminOauthAppsApi.PATH_ADMIN_O_AUTH_APPS_UPDATE_O_AUTH_APP,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<OAuthApp> adminOAuthAppsUpdateOAuthApp(
      @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("appId")
          String appId,
      @Parameter(name = "UpdateOAuthAppRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateOAuthAppRequest updateOAuthAppRequest);
}
