/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package saas.identity.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import saas.identity.shared.dto.ErrorResponse;
import saas.identity.shared.dto.LoginRequest;
import saas.identity.shared.dto.LoginResponse;
import saas.identity.shared.dto.OidcCallbackRequest;
import saas.identity.shared.dto.TokenRequest;
import saas.identity.shared.dto.TokenResponse;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-12T13:11:49.950871300+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "auth", description = "the auth API")
public interface AuthApi {

  String PATH_AUTH_LOGIN = "/api/v1/auth/login";

  /**
   * POST /api/v1/auth/login
   *
   * @param loginRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authLogin",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = LoginResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_AUTH_LOGIN,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<LoginResponse> authLogin(
      @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody
          LoginRequest loginRequest);

  String PATH_AUTH_LOGOUT = "/api/v1/auth/logout";

  /**
   * POST /api/v1/auth/logout
   *
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204)
   */
  @Operation(
      operationId = "authLogout",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. ")
      })
  @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_AUTH_LOGOUT)
  ResponseEntity<Void> authLogout();

  String PATH_AUTH_OIDC_CALLBACK = "/api/v1/auth/oidc/callback";

  /**
   * POST /api/v1/auth/oidc/callback
   *
   * @param oidcCallbackRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authOidcCallback",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TokenResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_AUTH_OIDC_CALLBACK,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<TokenResponse> authOidcCallback(
      @Parameter(name = "OidcCallbackRequest", description = "", required = true)
          @Valid
          @RequestBody
          OidcCallbackRequest oidcCallbackRequest);

  String PATH_AUTH_REFRESH_TOKEN = "/api/v1/auth/refresh";

  /**
   * POST /api/v1/auth/refresh
   *
   * @param tokenRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authRefreshToken",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TokenResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_AUTH_REFRESH_TOKEN,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<TokenResponse> authRefreshToken(
      @Parameter(name = "TokenRequest", description = "", required = true) @Valid @RequestBody
          TokenRequest tokenRequest);
}
