/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package saas.identity.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import saas.identity.shared.dto.CreateUserRequest;
import saas.identity.shared.dto.ErrorResponse;
import saas.identity.shared.dto.TenantUsersAssignRolesRequest;
import saas.identity.shared.dto.TenantUsersChangeUserStatusRequest;
import saas.identity.shared.dto.TenantUsersInviteUserRequest;
import saas.identity.shared.dto.TenantUsersListUsers200Response;
import saas.identity.shared.dto.UpdateUserRequest;
import saas.identity.shared.dto.User;
import saas.identity.shared.dto.UserStatus;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-13T19:43:32.481885100+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "tenant-users", description = "the tenant-users API")
public interface TenantUsersApi {

  String PATH_TENANT_USERS_ASSIGN_ROLES = "/api/v1/tenants/{tenantId}/users/{userId}/roles";

  /**
   * PUT /api/v1/tenants/{tenantId}/users/{userId}/roles
   *
   * @param tenantId (required)
   * @param userId (required)
   * @param tenantUsersAssignRolesRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantUsersAssignRoles",
      tags = {"tenant-users"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = User.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = TenantUsersApi.PATH_TENANT_USERS_ASSIGN_ROLES,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<User> tenantUsersAssignRoles(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("userId")
          String userId,
      @Parameter(name = "TenantUsersAssignRolesRequest", description = "", required = true)
          @Valid
          @RequestBody
          TenantUsersAssignRolesRequest tenantUsersAssignRolesRequest);

  String PATH_TENANT_USERS_CHANGE_USER_STATUS = "/api/v1/tenants/{tenantId}/users/{userId}/status";

  /**
   * PATCH /api/v1/tenants/{tenantId}/users/{userId}/status
   *
   * @param tenantId (required)
   * @param userId (required)
   * @param tenantUsersChangeUserStatusRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantUsersChangeUserStatus",
      tags = {"tenant-users"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = User.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PATCH,
      value = TenantUsersApi.PATH_TENANT_USERS_CHANGE_USER_STATUS,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<User> tenantUsersChangeUserStatus(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("userId")
          String userId,
      @Parameter(name = "TenantUsersChangeUserStatusRequest", description = "", required = true)
          @Valid
          @RequestBody
          TenantUsersChangeUserStatusRequest tenantUsersChangeUserStatusRequest);

  String PATH_TENANT_USERS_CREATE_USER = "/api/v1/tenants/{tenantId}/users";

  /**
   * POST /api/v1/tenants/{tenantId}/users
   *
   * @param tenantId (required)
   * @param createUserRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantUsersCreateUser",
      tags = {"tenant-users"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = User.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = TenantUsersApi.PATH_TENANT_USERS_CREATE_USER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<User> tenantUsersCreateUser(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "CreateUserRequest", description = "", required = true) @Valid @RequestBody
          CreateUserRequest createUserRequest);

  String PATH_TENANT_USERS_DELETE_USER = "/api/v1/tenants/{tenantId}/users/{userId}";

  /**
   * DELETE /api/v1/tenants/{tenantId}/users/{userId}
   *
   * @param tenantId (required)
   * @param userId (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "tenantUsersDeleteUser",
      tags = {"tenant-users"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = TenantUsersApi.PATH_TENANT_USERS_DELETE_USER,
      produces = {"application/json"})
  ResponseEntity<Void> tenantUsersDeleteUser(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("userId")
          String userId);

  String PATH_TENANT_USERS_GET_USER = "/api/v1/tenants/{tenantId}/users/{userId}";

  /**
   * GET /api/v1/tenants/{tenantId}/users/{userId}
   *
   * @param tenantId (required)
   * @param userId (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantUsersGetUser",
      tags = {"tenant-users"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = User.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = TenantUsersApi.PATH_TENANT_USERS_GET_USER,
      produces = {"application/json"})
  ResponseEntity<User> tenantUsersGetUser(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("userId")
          String userId);

  String PATH_TENANT_USERS_INVITE_USER = "/api/v1/tenants/{tenantId}/users/invitations";

  /**
   * POST /api/v1/tenants/{tenantId}/users/invitations
   *
   * @param tenantId (required)
   * @param tenantUsersInviteUserRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantUsersInviteUser",
      tags = {"tenant-users"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = User.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = TenantUsersApi.PATH_TENANT_USERS_INVITE_USER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<User> tenantUsersInviteUser(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "TenantUsersInviteUserRequest", description = "", required = true)
          @Valid
          @RequestBody
          TenantUsersInviteUserRequest tenantUsersInviteUserRequest);

  String PATH_TENANT_USERS_LIST_USERS = "/api/v1/tenants/{tenantId}/users";

  /**
   * GET /api/v1/tenants/{tenantId}/users
   *
   * @param tenantId (required)
   * @param page (optional)
   * @param pageSize (optional)
   * @param status (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantUsersListUsers",
      tags = {"tenant-users"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TenantUsersListUsers200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = TenantUsersApi.PATH_TENANT_USERS_LIST_USERS,
      produces = {"application/json"})
  ResponseEntity<TenantUsersListUsers200Response> tenantUsersListUsers(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "status", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "status", required = false)
          @Nullable
          UserStatus status);

  String PATH_TENANT_USERS_UPDATE_USER = "/api/v1/tenants/{tenantId}/users/{userId}";

  /**
   * PATCH /api/v1/tenants/{tenantId}/users/{userId}
   *
   * @param tenantId (required)
   * @param userId (required)
   * @param updateUserRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "tenantUsersUpdateUser",
      tags = {"tenant-users"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = User.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PATCH,
      value = TenantUsersApi.PATH_TENANT_USERS_UPDATE_USER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<User> tenantUsersUpdateUser(
      @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("tenantId")
          String tenantId,
      @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("userId")
          String userId,
      @Parameter(name = "UpdateUserRequest", description = "", required = true) @Valid @RequestBody
          UpdateUserRequest updateUserRequest);
}
